CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),      -- 총 7자리중 2자리는 소수점이하(실수영역)
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2)
    );

INSERT INTO EMP_DDL VALUES(9000, '안유진', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9001, '장원영', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9002, '가을', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9003, '리즈', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9004, '레이', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9005, '이서', 'IVE', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9006, '민지', '뉴진스', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9007, '해린', '뉴진스', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9008, '하니', '뉴진스', 9000, SYSDATE, 10000, 2000, 10);
INSERT INTO EMP_DDL VALUES(9009, '해인', '뉴진스', 9000, SYSDATE, 10000, 2000, 10);

INSERT INTO EMP_DDL VALUES(9010, '유나', '잇지', 9000, SYSDATE, 10000, 2000, 10, '+82010-1234-5678');
INSERT INTO EMP_DDL VALUES(9011, '예지', '잇지', 9000, SYSDATE, 10000, 2000, 1000, '+82010-1234-5678');

DELETE FROM EMP_DDL;

SELECT * FROM EMP_DDL
ORDER BY EMPNO;

-- 테이블 변경하는 ALTER 
-- ADD : 열 추가   (ADD + 추가 할 열 이름 + 데이터형)
-- RENAME : 열 이름 변경   (RENAME COLUMN + 기존 열이름 + TO  + 새 열이름)
-- MODIFY : 열의 데이터형 변경  (MODIFY + 열 이름 + 변경할 데이터형 )
-- DROP : 열을 제거   (DROP COLUMN + 지울 열 이름)

-- 테이블에 열 추가
ALTER TABLE EMP_DDL
ADD HP VARCHAR2(20);

-- 테이블의 열 이름 변경
ALTER TABLE EMP_DDL
RENAME COLUMN HP TO TEL;

-- 열의 데이터형 변경 : 새 조건에 맞지 않는 데이터가 있다면 형 변경이 되지 않음
ALTER TABLE EMP_DDL
MODIFY TEL VARCHAR2(16);

ALTER TABLE EMP_DDL
MODIFY DEPTNO NUMBER(4);

-- 열 제거 : 데이터가 있어도 삭제함.
ALTER TABLE EMP_DDL
DROP COLUMN TEL;

-- 테이블 이름을 변경하는 RENAME  (RENAME + 현재 테이블 이름 + TO + 새 테이블 이름)
RENAME EMP_DDL TO EMP_RENAME;

SELECT * FROM EMP_RENAME
ORDER BY EMPNO;

-- 테이블의 데이터를 삭제하는 TRUNCATE
TRUNCATE TABLE EMP_RENAME;   -- DDL 명령어 (ROLLBACK X)

DELETE FROM EMP_RENAME;  -- DML명령어 (ROLLBACK O), WHERE 절 사용으로 원하는 데이터만 삭제 가능

-- 테이블을 삭제하는 DROP
DROP TABLE EMP_RENAME;

-- 빈 값을 허용하지 않는 NOT NULL
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL) VALUES('KOKOKORKR', 'DLTPDND@12', NULL);
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL) VALUES('KOKOKORKI', 'DLTPDND@123', '010-1234-5678');
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL) VALUES('KOKOKORKY', NULL, '010-1234-5679');

SELECT * FROM TABLE_NOTNULL;

DROP TABLE TABLE_NOTNULL;

-- 중복 되지 않는 값 UNIQUE : NULL은 허용, 테이블 내에 여러 열에 존재 가능
-- UNIQUE NOT NULL : NULL 허용 하지 않음
-- PRIMARY KEY : NULL 허용 하지 않음, 테이블 내에 단 하나만 존재
CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DROP TABLE TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL) VALUES('KOKOKORK', 'DLTPDND@12', NULL);
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL) VALUES('KOKOKORK', 'DLTPDND@123', NULL);

SELECT * FROM TABLE_UNIQUE;

-- 다른 테이블과 관계를 맺는 FOREIGN KEY
-- 외래키는 서로 다른 테이블간 관계를 정의 하는데 사용하는 제약 조건
-- 참조하고 있는 기본 키의 데이터타입과 일치해야 하며 외래키로 참조되고 있는 기본 키는 삭제 할 수 없음
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) REFERENCES DEPT_FK(DEPTNO)
);

INSERT INTO DEPT_FK VALUES (10, '농구부', '서울');
INSERT INTO EMP_FK VALUES (9000, '강백호', '농구', 8000, 2300, 1200, 10);

SELECT * FROM 
EMP_FK E JOIN DEPT_FK D
ON E.DEPTNO = D.DEPTNO;

-- 데이터 형태와 범위를 정하는 CHECK
-- EX) ID  및 PASSWORD의 길이 제한
-- EX) 유효 값 범위 확인 (나이 / 성적 / 전화번호 / 이메일 등)

CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CHECK(LENGTH(LOGIN_PWD) >= 5),
    TEL VARCHAR2(20)
);

INSERT INTO TABLE_CHECK VALUES('KOREAZZANG', 'SBN1M', '010-1642-4511');

SELECT * FROM TABLE_CHECK;

-- DEFAULT 제약 조건 : 특정 열에 저장할 값이 지정되지 않은 경우 기본값을 지정
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CHECK(LENGTH(LOGIN_PWD) >= 5),
    TEL VARCHAR2(15) DEFAULT '010-0000-0000'
);
INSERT INTO TABLE_DEFAULT VALUES('KOREAZZANG1', 'SBN1M', NULL);
INSERT INTO TABLE_DEFAULT(LOGIN_ID, LOGIN_PWD) VALUES('KOREAZZANG1', 'SBN1M');
SELECT * FROM TABLE_DEFAULT;

-- 시퀀스 : 오라클에서 특정 규칙에 맞는 연속적인 숫자를 생성하는 객체
CREATE TABLE DEPT_SEQ1(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

CREATE SEQUENCE SEQ_DEPT_SEQ
INCREMENT BY 10  -- 증가 값
START WITH 10   -- 시작 값
MAXVALUE 90  -- 최대 값
MINVALUE 0     -- 최소 값
NOCYCLE
CACHE 2;

INSERT INTO DEPT_SEQ1 VALUES(SEQ_DEPT_SEQ.NEXTVAL,'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQ1;
INSERT INTO DEPT_SEQ1 VALUES(SEQ_DEPT_SEQ.NEXTVAL,'FRONT', 'BUSAN');
INSERT INTO DEPT_SEQ1 VALUES(SEQ_DEPT_SEQ.NEXTVAL,'FRO1NT', 'BUSAN2');

DELETE FROM DEPT_SEQ1 WHERE DEPTNO = 50;